name: ❓ Question
description: Ask a question
labels: [question]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!
  - type: textarea
    id: question-description
    attributes:
      label: Description of the question
      description: 'As a user I would like to know [question]. Thanks!'
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/ds-horizon/react-native-performance-tracker/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Check that there isn't [already an issue](https://github.com/ds-horizon/react-native-performance-tracker/issues) asking the same question.
          required: true